--- 
apiVersion: v1
kind: Pod
metadata: 
  labels: 
    app: myapp
    type: front-end
  name: nginx-test-pod
  namespace: pratheesh
spec: 
  containers: 
    - 
      image: nginx
      name: nginx-container

