apiVersion: apps/v1
kind: Deployment
metadata:
     name: deployment-postgres
     labels:
        app: postgres-app
     namespace: pratheesh
spec:
   replicas: 2
   template:
       metadata:
          name: postgres-pod
          labels:
                  app: postgres-app
       spec:
           containers:
                  - name: postgres
                    image: postgres:9.4
                    ports:
                       - containerPort: 5432
                    env:
                      - name: POSTGRES_HOST_AUTH_METHOD
                        value: trust
   selector:
           matchLabels:
                   app: postgres-app



