apiVersion: apps/v1
kind: Deployment
metadata:
     name: deployment-redis
     labels:
         app: redis-app
     namespace: pratheesh
spec:
    replicas: 2
    template:
         metadata:
            name: redis-pod
            labels:
               app: redis-app
         spec:
            containers:
                 - name: redis-container
                   image: redis
                   ports:
                     - containerPort: 6379
    selector:
         matchLabels:
               app: redis-app

