apiVersion: v1
kind: Service
metadata:
    name: service-voting-app
    namespace: pratheesh
spec:
    type: NodePort
    ports:
     - targetPort: 80
       port: 80
    selector:
        app: voting-app

