apiVersion: apps/v1
kind: Deployment
metadata:
       name: deployment-votingapp
       namespace: pratheesh
       labels:
            app: voting-app
spec:
    replicas: 2
    selector:
         matchLabels:
               app: voting-app
    template:
         metadata:
              name: voting-app-pod
              labels:
                  app: voting-app
         spec:    
            containers:
                  - name: voting-app-container
                    image: dockersamples/examplevotingapp_vote
                    ports:
                        - containerPort: 80

