apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
     name: sample-sc
provisioner: kubernetes.io/aws-ebs
parameters: 
   type: gp2 
reclaimPolicy: Delete #default
allowVolumeExpansion: true
volumeBindingMode: Immediate  #default value 
