apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    labels:
       type: frontend
spec:
  ports:
     - port: 80
       name: web
  type: ClusterIP
  clusterIP: None
  selector:
      type: frontend  
             
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: sample-nginx
    labels:
      type: frontend
spec:
   replicas: 2
   template:
      metadata:
        labels:
           type: frontend
      spec:
         containers:
            - name: nginx
              image: nginx
              volumeMounts:
                  - name: test-mount
                    mountPath: "/usr/share/nginx/html"
   selector:
      matchLabels:
         type: frontend
   serviceName: "nginx-service"
   volumeClaimTemplates:
           - metadata:
                  name: test-mount
             spec:
               accessModes:
                      - ReadWriteOnce
               storageClassName: sample-sc
               resources:
                    requests:
                        storage: 1Gi

